[swayfx]
src.git = "https://github.com/WillPower3309/swayfx"
src.branch = "master"
fetch.github = "WillPower3309/swayfx"

[nil]
src.git = "https://github.com/oxalica/nil"
src.branch = "main"
fetch.github = "oxalica/nil"
