# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  asd = {
    pname = "asd";
    version = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
    src = fetchFromGitHub {
      owner = "graysky2";
      repo = "anything-sync-daemon";
      rev = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
      fetchSubmodules = false;
      sha256 = "sha256-6nfaAMH5YgK6gimuZ8j1zWLTDOi11KIwW7Bf0Iwh7+I=";
    };
    date = "2022-03-26";
  };
  cargo-asm = {
    pname = "cargo-asm";
    version = "577f890ebd4a09c8265710261e976fe7bfce8668";
    src = fetchFromGitHub {
      owner = "gnzlbg";
      repo = "cargo-asm";
      rev = "577f890ebd4a09c8265710261e976fe7bfce8668";
      fetchSubmodules = false;
      sha256 = "sha256-KwOeX+BtS8xFUYqNSz8VM83qe7XWp18wTbq216v+07g=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-asm-577f890ebd4a09c8265710261e976fe7bfce8668/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2019-12-24";
  };
  cargo-call-stack = {
    pname = "cargo-call-stack";
    version = "49080d56b827573f1e19ff127401e312d08f138c";
    src = fetchFromGitHub {
      owner = "japaric";
      repo = "cargo-call-stack";
      rev = "49080d56b827573f1e19ff127401e312d08f138c";
      fetchSubmodules = false;
      sha256 = "sha256-UVKu9e2MYAjnKAAanj5xRUI1kQ7dd/+xMLosB21nQeM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-call-stack-49080d56b827573f1e19ff127401e312d08f138c/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-10-28";
  };
  cargo-disasm = {
    pname = "cargo-disasm";
    version = "86548e27c95200d860789824c6404f5382fc393b";
    src = fetchFromGitHub {
      owner = "ExPixel";
      repo = "cargo-disasm";
      rev = "86548e27c95200d860789824c6404f5382fc393b";
      fetchSubmodules = true;
      sha256 = "sha256-HbsglAQEoxjDKF/dNvKpB8UfbNsYFJ9briLn65Nf3bA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-disasm-86548e27c95200d860789824c6404f5382fc393b/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-06-19";
  };
  ccsum = {
    pname = "ccsum";
    version = "d7ec759c37ffa5164a4395e74e4c7338ebe25fc4";
    src = fetchFromGitHub {
      owner = "sevenc-nanashi";
      repo = "ccsum";
      rev = "d7ec759c37ffa5164a4395e74e4c7338ebe25fc4";
      fetchSubmodules = false;
      sha256 = "sha256-iaxxwa+yLmQXPMW+FLhT9RjEv2KwXMvRGp08Lsw4UMk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./ccsum-d7ec759c37ffa5164a4395e74e4c7338ebe25fc4/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2026-01-16";
  };
  defmt-print = {
    pname = "defmt-print";
    version = "023449c35f68b9dfc2e00437e47353755d5189ef";
    src = fetchFromGitHub {
      owner = "knurling-rs";
      repo = "defmt";
      rev = "023449c35f68b9dfc2e00437e47353755d5189ef";
      fetchSubmodules = false;
      sha256 = "sha256-kmnU7PCTtSJ6b/wNrR+38t29yf+KjWLRmGUZXW2/DsI=";
    };
    date = "2025-12-12";
  };
  memvis = {
    pname = "memvis";
    version = "4fdb38d33278bd7739c5b24349b39a72ad768a1b";
    src = fetchFromGitHub {
      owner = "ibuki2003";
      repo = "memvis";
      rev = "4fdb38d33278bd7739c5b24349b39a72ad768a1b";
      fetchSubmodules = false;
      sha256 = "sha256-FFigFsgHYuZo+OusNsf5sPQp/7BWf6sclHWHx/bN58k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./memvis-4fdb38d33278bd7739c5b24349b39a72ad768a1b/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-07-15";
  };
  nu-plugin-bexpand = {
    pname = "nu-plugin-bexpand";
    version = "07111c423a1a5e013eb108253068ee36dfcbbfbb";
    src = fetchgit {
      url = "https://forge.axfive.net/Taylor/nu-plugin-bexpand.git";
      rev = "07111c423a1a5e013eb108253068ee36dfcbbfbb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PWwE+blEc4/LppIyyF4V6t4GmwJgpyWHgnPXVzwfAm0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-plugin-bexpand-07111c423a1a5e013eb108253068ee36dfcbbfbb/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-11-29";
  };
  quickshell = {
    pname = "quickshell";
    version = "d03c59768c680f052dff6e7a7918bbf990b0f743";
    src = fetchgit {
      url = "https://git.outfoxxed.me/quickshell/quickshell.git";
      rev = "d03c59768c680f052dff6e7a7918bbf990b0f743";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DxN7v8g8DO8gGJmgBJMo3fsSR3HEs+DFCXeKeHq61zA=";
    };
    date = "2026-01-15";
  };
  skkemoji = {
    pname = "skkemoji";
    version = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
    src = fetchFromGitHub {
      owner = "uasi";
      repo = "skk-emoji-jisyo";
      rev = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
      fetchSubmodules = false;
      sha256 = "sha256-y/AuoOCoCDkhhCwBm9dSUajeL3Q/N47GE1RBXNhj5F0=";
    };
    date = "2025-01-02";
  };
  slice = {
    pname = "slice";
    version = "f73dec5b51fb7a33c99b5e6080f4083ef68507b4";
    src = fetchFromGitHub {
      owner = "ibuki2003";
      repo = "slice";
      rev = "f73dec5b51fb7a33c99b5e6080f4083ef68507b4";
      fetchSubmodules = false;
      sha256 = "sha256-3pK13yaziuJ4GFl2uKYBwSIGpEehun17vYmGWbVO4lE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./slice-f73dec5b51fb7a33c99b5e6080f4083ef68507b4/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-09-18";
  };
}
