# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  asd = {
    pname = "asd";
    version = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
    src = fetchFromGitHub {
      owner = "graysky2";
      repo = "anything-sync-daemon";
      rev = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
      fetchSubmodules = false;
      sha256 = "sha256-6nfaAMH5YgK6gimuZ8j1zWLTDOi11KIwW7Bf0Iwh7+I=";
    };
    date = "2022-03-26";
  };
  cargo-asm = {
    pname = "cargo-asm";
    version = "577f890ebd4a09c8265710261e976fe7bfce8668";
    src = fetchFromGitHub {
      owner = "gnzlbg";
      repo = "cargo-asm";
      rev = "577f890ebd4a09c8265710261e976fe7bfce8668";
      fetchSubmodules = false;
      sha256 = "sha256-KwOeX+BtS8xFUYqNSz8VM83qe7XWp18wTbq216v+07g=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-KwOeX+BtS8xFUYqNSz8VM83qe7XWp18wTbq216v+07g=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2019-12-24";
  };
  cargo-call-stack = {
    pname = "cargo-call-stack";
    version = "49080d56b827573f1e19ff127401e312d08f138c";
    src = fetchFromGitHub {
      owner = "japaric";
      repo = "cargo-call-stack";
      rev = "49080d56b827573f1e19ff127401e312d08f138c";
      fetchSubmodules = false;
      sha256 = "sha256-UVKu9e2MYAjnKAAanj5xRUI1kQ7dd/+xMLosB21nQeM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-UVKu9e2MYAjnKAAanj5xRUI1kQ7dd_+xMLosB21nQeM=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2024-10-28";
  };
  cargo-disasm = {
    pname = "cargo-disasm";
    version = "86548e27c95200d860789824c6404f5382fc393b";
    src = fetchFromGitHub {
      owner = "ExPixel";
      repo = "cargo-disasm";
      rev = "86548e27c95200d860789824c6404f5382fc393b";
      fetchSubmodules = true;
      sha256 = "sha256-HbsglAQEoxjDKF/dNvKpB8UfbNsYFJ9briLn65Nf3bA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-HbsglAQEoxjDKF_dNvKpB8UfbNsYFJ9briLn65Nf3bA=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2023-06-19";
  };
  ccsum = {
    pname = "ccsum";
    version = "0f7732d259b72e55bb0e12b10ee5a723fb91214d";
    src = fetchFromGitHub {
      owner = "sevenc-nanashi";
      repo = "ccsum";
      rev = "0f7732d259b72e55bb0e12b10ee5a723fb91214d";
      fetchSubmodules = false;
      sha256 = "sha256-IH4JCnbIalunlcwSwZS/zlA1YT33hjzg3Hl3AH7Z4ag=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-IH4JCnbIalunlcwSwZS_zlA1YT33hjzg3Hl3AH7Z4ag=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-24";
  };
  defmt-print = {
    pname = "defmt-print";
    version = "5dc9b1ef6d9c63a6859dae36f7230df51ff2b917";
    src = fetchFromGitHub {
      owner = "knurling-rs";
      repo = "defmt";
      rev = "5dc9b1ef6d9c63a6859dae36f7230df51ff2b917";
      fetchSubmodules = false;
      sha256 = "sha256-Iey02Z3Ug7FfCUWTR1U4FPvfqAt1CZdVbBTyofS18QA=";
    };
    date = "2026-09-08";
  };
  memvis = {
    pname = "memvis";
    version = "4fdb38d33278bd7739c5b24349b39a72ad768a1b";
    src = fetchFromGitHub {
      owner = "ibuki2003";
      repo = "memvis";
      rev = "4fdb38d33278bd7739c5b24349b39a72ad768a1b";
      fetchSubmodules = false;
      sha256 = "sha256-FFigFsgHYuZo+OusNsf5sPQp/7BWf6sclHWHx/bN58k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-FFigFsgHYuZo+OusNsf5sPQp_7BWf6sclHWHx_bN58k=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2025-07-15";
  };
  niri = {
    pname = "niri";
    version = "e1d3b0c47ce5bb77f16e5006aba604d23b233649";
    src = fetchFromGitHub {
      owner = "niri-wm";
      repo = "niri";
      rev = "e1d3b0c47ce5bb77f16e5006aba604d23b233649";
      fetchSubmodules = false;
      sha256 = "sha256-DHSudbdHVLNvSN3yhq7u0r68ZONHhWahkL0l30kD0hc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-DHSudbdHVLNvSN3yhq7u0r68ZONHhWahkL0l30kD0hc=/Cargo.lock";
      outputHashes = {
        "smithay-0.7.0" = "sha256-9zYFSdwBkuADMTR06KJ35C+vswDrLa87vGI9Far83xE=";
      };
    };
    date = "2026-09-14";
  };
  quickshell = {
    pname = "quickshell";
    version = "86b4275879b32bf58dc89035452313919cd89bd2";
    src = fetchgit {
      url = "https://git.outfoxxed.me/quickshell/quickshell.git";
      rev = "86b4275879b32bf58dc89035452313919cd89bd2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aTC/VZh0Qj7FN1ej9HGp31mGVA27T7BZ+vMhxDVY77U=";
    };
    date = "2026-09-13";
  };
  skkemoji = {
    pname = "skkemoji";
    version = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
    src = fetchFromGitHub {
      owner = "uasi";
      repo = "skk-emoji-jisyo";
      rev = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
      fetchSubmodules = false;
      sha256 = "sha256-y/AuoOCoCDkhhCwBm9dSUajeL3Q/N47GE1RBXNhj5F0=";
    };
    date = "2025-01-02";
  };
  slice = {
    pname = "slice";
    version = "f73dec5b51fb7a33c99b5e6080f4083ef68507b4";
    src = fetchFromGitHub {
      owner = "ibuki2003";
      repo = "slice";
      rev = "f73dec5b51fb7a33c99b5e6080f4083ef68507b4";
      fetchSubmodules = false;
      sha256 = "sha256-3pK13yaziuJ4GFl2uKYBwSIGpEehun17vYmGWbVO4lE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-3pK13yaziuJ4GFl2uKYBwSIGpEehun17vYmGWbVO4lE=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2025-09-18";
  };
}
