# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  asd = {
    pname = "asd";
    version = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
    src = fetchFromGitHub {
      owner = "graysky2";
      repo = "anything-sync-daemon";
      rev = "19204c7fd227cd298f30b923f9b969d5d31f3e54";
      fetchSubmodules = false;
      sha256 = "sha256-6nfaAMH5YgK6gimuZ8j1zWLTDOi11KIwW7Bf0Iwh7+I=";
    };
    date = "2022-03-26";
  };
  skkemoji = {
    pname = "skkemoji";
    version = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
    src = fetchFromGitHub {
      owner = "uasi";
      repo = "skk-emoji-jisyo";
      rev = "18ff911d0dc445dbc8fbc4c5122874d08e56781b";
      fetchSubmodules = false;
      sha256 = "sha256-y/AuoOCoCDkhhCwBm9dSUajeL3Q/N47GE1RBXNhj5F0=";
    };
    date = "2025-01-02";
  };
}
