[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
colorscheme molokai
autocmd ColorScheme * hi Comment ctermfg=102
autocmd ColorScheme * hi Visual ctermbg=240
autocmd ColorScheme * hi MatchParen cterm=bold ctermfg=208 ctermbg=233
autocmd ColorScheme * hi Pmenu ctermbg=237 ctermfg=4
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
autocmd ColorScheme iceberg hi Visual ctermbg=237
autocmd ColorScheme iceberg hi NonText ctermfg=240
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {}
let g:lightline.active = {
\ 'left': [
\   ['mode', 'paste'],
\   ['gitbranch', 'readonly', 'relativepath', 'modified'],
\   ['lsp_diagnostics'],
\ ],
\ 'right': [
\   ['lineinfo'],
\   ['percent'],
\   ['im_state', 'fileformat', 'fileencoding', 'filetype'],
\ ],
\}
let g:lightline.inactive = {
\ 'left':  [ ['filename', 'modified'] ],
\ 'right': [ ['lineinfo'] ],
\}
let g:lightline.component = {
\ 'lineinfo': '%3l:%-2v%<',
\}
let g:lightline.component_function = {
\ 'gitbranch': 'FugitiveHead',
\ 'lsp_diagnostics': 'LspDiagnosticsCount',
\ 'im_state': 'LLIMState',
\}

function! LspDiagnosticsCount()
    let counts = lsp#get_buffer_diagnostics_counts()
    let ret = []

    if counts.error
        call add(ret, 'E' . (counts.error))
    endif

    if counts.warning
        call add(ret, 'W' . (counts.warning))
    endif

    if counts.information
        call add(ret, 'I' . (counts.information))
    endif

    if counts.hint
        call add(ret, 'H' . (counts.hint))
    endif

    return join(ret, ' ')
endfunction

function! LLIMState()
    if exists('g:IMState') && g:IMState
        return 'JP'
    else
        return ''
    endif
endfunction
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
autocmd ColorScheme * hi IndentGuidesOdd  ctermbg=234
autocmd ColorScheme * hi IndentGuidesEven ctermbg=235
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

