[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'ncm2/float-preview.nvim'
if = "has('nvim-0.4')"
hook_add = '''
let g:float_preview#docked = 0
'''

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
let g:neosnippet#disable_runtime_snippets = {
\ '_' : 1,
\}
let g:neosnippet#snippets_directory = expand('~/.nvim/snippets')

let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#enable_complete_done = 1

imap <expr> <Tab> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
smap <expr> <Tab> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
'''

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_post_source = '''
lua require('lsp_servers')
'''

#[[plugins]]
#repo = 'nvim-lua/completion-nvim'
#hook_add = '''
#let g:completion_enable_auto_popup = 1
#'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-lsp'

