[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
hook_add = '''
" insert mode に入った時に 'filetype' を切り換える。
" カーソル移動時の自動切り替えを無効化
let g:precious_enable_switch_CursorMoved = {
\ '*' : 0,
\ 'help': 1
\}
let g:precious_enable_switch_CursorMoved_i = {
\ "*" : 0
\}

" insert に入った時にスイッチし、抜けた時に元に戻す
augroup fuwa_precious
  autocmd!
  autocmd InsertEnter * :PreciousSwitch
  " autocmd InsertLeave * :PreciousReset
augroup END
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
let g:highlightedyank_highlight_duration = 300
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
map <Leader>r <Plug>(operator-replace)
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

let g:easy_align_ignore_groups = ['String']
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'fuenor/im_control.vim'
hook_add = '''
if executable('fcitx-remote')
    let g:IM_CtrlMode = 6
endif

inoremap <silent> <C-k> <C-r>=IMState('FixMode')<CR>
'''
lazy = 1
on_i = 1

[[plugins]]
repo = 'mrtazz/simplenote.vim'
if = 'exists("g:SimplenoteUsername")'
hook_add = '''
let g:SimplenoteFiletype = "markdown"
let g:SimplenoteVertical = 1
'''

[[plugins]]
repo = 'monaqa/dial.nvim'
hook_add = '''
nmap <C-a> <Plug>(dial-increment)
nmap <C-x> <Plug>(dial-decrement)
vmap <C-a> <Plug>(dial-increment)
vmap <C-x> <Plug>(dial-decrement)
vmap g<C-a> <Plug>(dial-increment-additional)
vmap g<C-x> <Plug>(dial-decrement-additional)
'''
hook_post_source = 'lua require("dial_config")'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'whatyouhide/vim-textobj-xmlattr'

[[plugins]]
repo = 'subnut/nvim-ghost.nvim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_show_hidden = 1
let g:ctrlp_follow_symlinks = 1
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
if = '&termguicolors'
hook_post_source = '''
lua require('nvim-colorizer')
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_i = 1
hook_add = '''
let g:table_mode_corner = '|'
'''
hook_post_source = 'TableModeEnable'

