[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
let g:NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
nnoremap <F4> :NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
let g:NERDTreeGitStatusIndicatorMapCustom = {
\ 'Modified' : '*',
\ 'Dirty'    : '*',
\ 'Staged'   : '+',
\ 'Renamed'  : '>',
\ 'Unmerged' : 'C',
\ 'Untracked': '!',
\ }
'''
