#!/usr/bin/env bash
type=$(wl-paste -l | grep '^image/' -m 1)
if [[ $? -eq 0 ]]; then
  file=$(mktemp -p /tmp pbimg-XXXXXX)
  trap 'rm -f "$file"' EXIT
  wl-paste -t $type > $file
  imv $file
else
  notify-send "not an image"
fi
